import type { Metadata } from "next";
// import { Geist, Geist_Mono, poppins } from "next/font/google";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import NextAuthSessionProvider from "../provider/NextAuthSessionProvider";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// 1
//2

const poppins = Poppins({
  weight: ["400", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: "Learn to NextJS",
    template: "%s || Learn to NextJS",
  },
  keywords: ["Next.js", "React", "JavaScript", "Learnig", "Playground"],

  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <NextAuthSessionProvider>
        <body className={`${poppins.className} antialiased`}>
          <Navbar />
          <main className="min-h-[calc(100vh-320px)]">{children}</main>
          <Footer />
        </body>
      </NextAuthSessionProvider>
    </html>
  );
}
